name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                node-version: [18]
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
                include:
                    - node-version: 18
                      operating-system: ubuntu-latest
                    - node-version: 18
                      operating-system: windows-latest
                    - node-version: 18
                      operating-system: macos-latest
                #exlude:
                    #- node-version: 18
                    #  operating-system: windows-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build